from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = REPO_ROOT / "results"
PAPER_DIR = REPO_ROOT / "paper"
TABLES_DIR = PAPER_DIR / "tables"
FIGURES_DIR = PAPER_DIR / "figures"


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt(x: float, nd: int = 4) -> str:
    # Keep small tables readable in ACL two-column.
    if x is None:
        return "-"
    return f"{x:.{nd}f}"


def _escape_latex(s: str) -> str:
    # Minimal escaping for metric names / labels.
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
        .replace("#", "\\#")
    )


@dataclass(frozen=True)
class MetricRow:
    metric: str
    full_mean: float
    other_mean: float
    diff: float
    q_value: float
    delta: float


def load_full_vs_strong_prompt() -> List[MetricRow]:
    path = RESULTS_DIR / "comparison_full_vs_strong_prompt.json"
    data = _read_json(path)
    rows: List[MetricRow] = []
    for metric, info in data["comparison_results"].items():
        full_mean = float(info["full_system_mean"])
        base_mean = float(info["baseline_mean"])
        diff = float(info["improvement"])
        q = float(info.get("wilcoxon_corrected", {}).get("q_value", 1.0))
        delta = float(info.get("cliffs_delta", 0.0))
        rows.append(
            MetricRow(
                metric=metric,
                full_mean=full_mean,
                other_mean=base_mean,
                diff=diff,
                q_value=q,
                delta=delta,
            )
        )
    # Show the most paper-relevant metrics first: semantic/deliverability/user-facing.
    order = [
        "S_sem",
        "S_ps",
        "S_uj",
        "S_hyp",
        "S_bi",
        "S_tab",
        "S_biz",
        "S_tech",
        "S_risk",
        "S_comp",
        "S_mm",
        "S_expert",
        "S_var",
    ]
    rows.sort(key=lambda r: order.index(r.metric) if r.metric in order else 999)
    return rows


def write_table_full_vs_strong_prompt(rows: List[MetricRow], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/export_paper_assets.py")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Metric & Full & StrongPrompt & $\\Delta$ & $q$ \\\\")
    lines.append("\\midrule")
    for r in rows:
        metric = _escape_latex(r.metric)
        # Highlight corrected-significant results.
        q_str = _fmt(r.q_value, 4)
        if r.q_value < 0.05:
            q_str = f"\\textbf{{{q_str}}}"
        lines.append(
            f"{metric} & {_fmt(r.full_mean,4)} & {_fmt(r.other_mean,4)} & {_fmt(r.diff,4)} & {q_str} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Full system vs. StrongPrompt baseline on 15 briefs. "
        "$\\Delta$ = Full $-$ StrongPrompt. $q$ is Holm--Bonferroni corrected Wilcoxon p-value.}"
    )
    lines.append("\\label{tab:full-vs-strong}")
    lines.append("\\end{table}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_table_ablation_summary(out_path: Path) -> None:
    """
    Small ablation table focusing on the key ablation that changes behavior:
    removing the table agent should drop S_tab sharply.
    """
    data = _read_json(RESULTS_DIR / "ablation" / "ablation_analysis.json")
    # Pick a compact subset of metrics that matter for claims.
    metrics = ["S_sem", "S_ps", "S_uj", "S_hyp", "S_tab", "S_bi"]
    configs = ["no_table", "no_consistency", "no_alignment", "no_vision", "async_queue"]

    def get_mean(config: str, metric: str) -> float:
        return float(data["comparison_results"][config][metric]["ablation_mean"])

    full_means: Dict[str, float] = {}
    for m in metrics:
        # full_system_mean is stored per config; take from any config present
        full_means[m] = float(data["comparison_results"]["async_queue"][m]["full_system_mean"])

    lines: List[str] = []
    lines.append("% Auto-generated by scripts/export_paper_assets.py")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    col_spec = "l" + "r" * (1 + len(configs))
    lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
    lines.append("\\toprule")
    header = ["Metric", "Full"] + [c.replace("_", "\\_") for c in configs]
    lines.append(" & ".join(header) + " \\\\")
    lines.append("\\midrule")
    for m in metrics:
        row = [_escape_latex(m), _fmt(full_means[m], 4)]
        for c in configs:
            val = get_mean(c, m)
            cell = _fmt(val, 4)
            # Emphasize the ablation that removes tables.
            if m == "S_tab" and c == "no_table":
                cell = f"\\textbf{{{cell}}}"
            row.append(cell)
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Ablation summary (means over 15 briefs). "
        "Removing the Table agent (\\texttt{no\\_table}) eliminates tables by design (bold).}"
    )
    lines.append("\\label{tab:ablation-summary}")
    lines.append("\\end{table*}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def copy_figures() -> List[Tuple[str, str]]:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    src_dir = RESULTS_DIR / "visualizations"
    mapping: List[Tuple[str, str]] = []
    for name in [
        "ablation_comparison.png",
        "ablation_heatmap.png",
        "statistical_significance.png",
        "full_vs_baseline_comparison.png",
        "full_vs_strong_prompt_comparison.png",
    ]:
        src = src_dir / name
        if not src.exists():
            continue
        dst = FIGURES_DIR / name
        shutil.copyfile(src, dst)
        mapping.append((str(src), str(dst)))
    return mapping


def main() -> None:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    rows = load_full_vs_strong_prompt()
    write_table_full_vs_strong_prompt(rows, TABLES_DIR / "full_vs_strong_prompt.tex")
    write_table_ablation_summary(TABLES_DIR / "ablation_summary.tex")
    copied = copy_figures()

    print(f"[ok] wrote {TABLES_DIR / 'full_vs_strong_prompt.tex'}")
    print(f"[ok] wrote {TABLES_DIR / 'ablation_summary.tex'}")
    if copied:
        print("[ok] copied figures:")
        for src, dst in copied:
            print(f"  - {src} -> {dst}")
    else:
        print("[warn] no figures copied (results/visualizations missing?)")


if __name__ == "__main__":
    main()


